server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://207.154.255.31:5432/cooks_corner
    username: postgres
    password: digitalocean
#    url: jdbc:postgresql://localhost:5432/cooks_corner
#    username: postgres
#    password: ronaldinho80
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect